import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Benchmark',
      items: [
        {
          type: 'autogenerated',
          dirName: 'benchmark',
        },
      ],
    },
  ],
};

export default sidebars;
