/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserProfileRouteImport } from './routes/user-profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as IndexRouteImport } from './routes/index'

const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user-profile',
  path: '/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/user-profile': typeof UserProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/user-profile': typeof UserProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/user-profile': typeof UserProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/memories' | '/sessions' | '/settings' | '/user-profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/memories' | '/sessions' | '/settings' | '/user-profile'
  id:
    | '__root__'
    | '/'
    | '/memories'
    | '/sessions'
    | '/settings'
    | '/user-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoriesRoute: typeof MemoriesRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  UserProfileRoute: typeof UserProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-profile': {
      id: '/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoriesRoute: MemoriesRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  UserProfileRoute: UserProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
