#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
# shellcheck disable=SC1091
. "$SCRIPT_DIR/common.sh"

echo "PowerMem Codex plugin init"
echo "Data dir: $DATA_DIR"

BOOTSTRAP_PYTHON=$(choose_python) || {
  echo "No Python >= 3.11 interpreter found. Set POWERMEM_INIT_PYTHON=/path/to/python3.11 and retry." >&2
  exit 1
}
echo "Bootstrap Python: $BOOTSTRAP_PYTHON ($(python_version "$BOOTSTRAP_PYTHON"))"

create_env_file() {
  "$BOOTSTRAP_PYTHON" - "$ENV_FILE" "$DATA_DIR" <<'PY'
import os
import sys
from pathlib import Path

env_path = Path(sys.argv[1])
data_dir = Path(sys.argv[2])

provider = os.environ.get("POWERMEM_INIT_LLM_PROVIDER", "").strip().lower()
model = os.environ.get("POWERMEM_INIT_LLM_MODEL", "").strip()
api_key = os.environ.get("POWERMEM_INIT_LLM_API_KEY", "").strip()
base_url = os.environ.get("POWERMEM_INIT_LLM_BASE_URL", "").strip()

if not api_key:
    for key in ("OPENAI_API_KEY", "ANTHROPIC_API_KEY", "DASHSCOPE_API_KEY"):
        value = os.environ.get(key, "").strip()
        if value:
            api_key = value
            if not provider:
                provider = {
                    "OPENAI_API_KEY": "openai",
                    "ANTHROPIC_API_KEY": "anthropic",
                    "DASHSCOPE_API_KEY": "qwen",
                }[key]
            break

missing = []
if not provider:
    missing.append("POWERMEM_INIT_LLM_PROVIDER")
if not model:
    missing.append("POWERMEM_INIT_LLM_MODEL")
if provider not in {"ollama", "vllm"} and not api_key:
    missing.append("POWERMEM_INIT_LLM_API_KEY")

if missing:
    print("Missing configuration: " + ", ".join(missing), file=sys.stderr)
    print("Run init again with these environment variables set.", file=sys.stderr)
    sys.exit(2)

lines = [
    "# Generated by the PowerMem Codex plugin.",
    "DATABASE_PROVIDER=sqlite",
    f"SQLITE_PATH={data_dir / 'powermem.sqlite'}",
    "EMBEDDING_PROVIDER=default",
    f"LLM_PROVIDER={provider}",
    f"LLM_MODEL={model}",
]
if api_key:
    lines.append(f"LLM_API_KEY={api_key}")
if base_url:
    key = f"{provider.upper()}_LLM_BASE_URL"
    if provider == "qwen":
        key = "QWEN_LLM_BASE_URL"
    lines.append(f"{key}={base_url}")

env_path.parent.mkdir(parents=True, exist_ok=True)
env_path.write_text("\n".join(lines) + "\n")
print(f"Wrote {env_path} with provider={provider}, model={model}, api_key={'set' if api_key else 'not-required'}")
PY
}

if [ ! -f "$ENV_FILE" ]; then
  echo "Creating plugin .env from POWERMEM_INIT_* variables."
  create_env_file
else
  echo "Using existing plugin .env: $ENV_FILE"
fi

if [ ! -x "$(venv_powermem_mcp)" ]; then
  echo "Preparing plugin virtualenv."
  if [ ! -d "$VENV_DIR" ]; then
    "$BOOTSTRAP_PYTHON" -m venv "$VENV_DIR"
  fi
  PYTHON=$(venv_python)
  echo "Venv Python: $PYTHON ($(python_version "$PYTHON"))"
  "$PYTHON" -m pip install -U pip setuptools wheel
  PACKAGE=${POWERMEM_INIT_PACKAGE:-powermem}
  echo "Installing $PACKAGE"
  "$PYTHON" -m pip install "$PACKAGE" "fastmcp>=1.0"
else
  echo "Using existing plugin virtualenv: $VENV_DIR"
  PYTHON=$(venv_python)
  echo "Venv Python: $PYTHON ($(python_version "$PYTHON"))"
  "$PYTHON" - <<'PY' >/dev/null 2>&1 || "$PYTHON" -m pip install "fastmcp>=1.0"
import fastmcp  # noqa: F401
PY
fi

if [ ! -x "$(venv_powermem_mcp)" ]; then
  echo "powermem-mcp was not installed into the plugin venv." >&2
  echo "Install a powermem package that provides the powermem-mcp console script." >&2
  exit 1
fi

echo "Bundled MCP config is provided by $PLUGIN_ROOT/.mcp.json"

if [ "${POWERMEM_INIT_ENABLE_HOOKS:-0}" = "1" ] || [ "${POWERMEM_INIT_ENABLE_HOOKS:-}" = "true" ]; then
  "$BOOTSTRAP_PYTHON" - "$CODEX_HOOKS_FILE" "$PLUGIN_ROOT/hooks/hooks.codex.json" "$PLUGIN_ROOT" <<'PY'
import json
import sys
from pathlib import Path

hooks_path = Path(sys.argv[1]).expanduser()
manifest_path = Path(sys.argv[2])
plugin_root = str(Path(sys.argv[3]))
marker = "__powermem_codex_hook__"

if hooks_path.is_file():
    try:
        payload = json.loads(hooks_path.read_text())
        if not isinstance(payload, dict):
            payload = {}
    except Exception:
        payload = {}
else:
    payload = {}

hooks = payload.get("hooks")
if not isinstance(hooks, dict):
    hooks = {}
payload["hooks"] = hooks

manifest = json.loads(manifest_path.read_text())
source_hooks = manifest.get("hooks")
if not isinstance(source_hooks, dict):
    raise SystemExit("Invalid hook manifest: missing hooks object")

for event, entries in list(hooks.items()):
    if isinstance(entries, list):
        kept = [
            entry
            for entry in entries
            if not (isinstance(entry, dict) and entry.get(marker) is True)
        ]
        if kept:
            hooks[event] = kept
        else:
            hooks.pop(event, None)

for event, entries in source_hooks.items():
    if not isinstance(entries, list):
        continue
    resolved = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        next_entry = {
            key: value
            for key, value in entry.items()
            if key != "hooks"
        }
        next_entry[marker] = True
        next_hooks = []
        for handler in entry.get("hooks", []):
            if not isinstance(handler, dict):
                continue
            next_handler = dict(handler)
            command = str(next_handler.get("command", ""))
            next_handler["command"] = command.replace("${CLAUDE_PLUGIN_ROOT}", plugin_root)
            next_hooks.append(next_handler)
        if next_hooks:
            next_entry["hooks"] = next_hooks
            resolved.append(next_entry)
    if resolved:
        hooks[event] = [*(hooks.get(event) or []), *resolved]

hooks_path.parent.mkdir(parents=True, exist_ok=True)
hooks_path.write_text(json.dumps(payload, indent=2) + "\n")
print(f"Wrote Codex fallback hook config: {hooks_path}")
PY
else
  echo "Skipping user-scope Codex hooks. Plugin-local hooks are bundled; set POWERMEM_INIT_ENABLE_HOOKS=1 for the Desktop fallback."
fi

write_runtime_file

echo "PowerMem MCP command: $(venv_powermem_mcp)"
echo "Restart Codex so it reloads the installed PowerMem plugin."
